model:
  emb_size: 512
  num_heads: 8
  num_enc_layers: 6
  num_dec_layers: 6
  dropout: 0.1
  forward_expansion: 2048
  max_len: 110
train:
  batch_size: 64
  epochs: 30
  lr: 0.001
preprocess:
  max_size: 100_000_000
  min_freq: 2
  src_lang: "ru_core_news_sm"
  trg_lang: "en_core_web_sm"
  seed: 52